Show an error update engine status for all unknown states.
The primary reason for this patch is so that I can add a new UPDATE_STATUS
enum value to libcros without breaking the Chrome OS build with the following
error:

"Right now we get the following error with LKGR of Chrome:
update_observer.cc: In member function 'virtual void
chromeos::UpdateObserver::Changed(chromeos::UpdateLibrary*)':
update_observer.cc:26: error: enumeration value
'UPDATE_STATUS_REPORTING_ERROR_EVENT' not handled in switch"

BUG=560
TEST=emerged chromeos-chrome with modified libcros, unit tests

Review URL: http://codereview.chromium.org/3053010

git-svn-id: http://src.chromium.org/svn/trunk/src/chrome/browser@53409 4ff67af0-8c30-449e-8e8b-ad334ec8d88c