NaCl: Fix link time error when DISABLE_NACL is set
This fixes breakage on the ARM buildbot, introduced by r54113.
nacl::Close() is not available when DISABLE_NACL is set.

The error was:
nacl_process_host.cc: error: undefined reference to 'nacl::Close(int)'

BUG=none
TEST=none (no trybot for the ARM build)

Review URL: http://codereview.chromium.org/3023025

git-svn-id: http://src.chromium.org/svn/trunk/src/chrome/browser@54123 4ff67af0-8c30-449e-8e8b-ad334ec8d88c