Revert 205265 "payments dialog: remove edit links from Views UI"
Breaks Mac compile:
../../chrome/browser/ui/cocoa/autofill/autofill_section_container.mm:329:50: error: no member named 'editable' in 'autofill::SuggestionState'
  [suggestContainer_ setEditable:suggestionState.editable];
                                 ~~~~~~~~~~~~~~~ ^

> payments dialog: remove edit links from Views UI
> 
> BUG=245901
> R=aruslan@chromium.org, dbeam@chromium.org
> 
> Review URL: https://codereview.chromium.org/16521002

TBR=estade@chromium.org

Review URL: https://codereview.chromium.org/16751002

git-svn-id: http://src.chromium.org/svn/trunk/src/chrome/browser@205279 4ff67af0-8c30-449e-8e8b-ad334ec8d88c