Back out r58827. It caused browser_tests ExtensionApiTest.Rlz to fail.
Failures:

http://build.chromium.org/buildbot/waterfall/builders/XP%20Tests/builds/22649/steps/browser_tests/logs/stdio
http://build.chromium.org/buildbot/waterfall/builders/Vista%20Tests/builds/22157/steps/browser_tests/logs/stdio

( RUN      ) sendFinancialPing
(  FAILED  ) sendFinancialPing
Got EXTENSION_TEST_FAILED notification.
.\browser\extensions\extension_rlz_apitest.cc(67): error: Value of: RunExtensionTest("rlz")
  Actual: false
Expected: true
FAIL (no message)
    at Object.callback (chrome-extension://acmddjjmpkiijbjcdpchhmniojioobgh/test.js:147:63)
    at Object.<anonymous> (chrome/ExtensionProcessBindings:124:19)
[  FAILED  ] ExtensionApiTest.Rlz (1531 ms)

BUG=54294
TEST=green tests
TBR=rogerta@google.com
Review URL: http://codereview.chromium.org/3371006

git-svn-id: http://src.chromium.org/svn/trunk/src/chrome/browser@58839 4ff67af0-8c30-449e-8e8b-ad334ec8d88c