Revert r123906 "Screensaver at login screen."
This reverts commit e165130f2b6c70c9b0bf70d2e787ba9fb86e7655.

This broke chromeos gtk build.

chrome/browser/chromeos/ui/screensaver_extension_dialog.cc: In member function 'virtual void ScreensaverExtensionDialog::Show()':
chrome/browser/chromeos/ui/screensaver_extension_dialog.cc:112: error: 'ShowFullscreen' is not a member of 'ExtensionDialog'

TBR=rkc@chromium.org
BUG=none
TEST=none

Review URL: https://chromiumcodereview.appspot.com/9488001

git-svn-id: http://src.chromium.org/svn/trunk/src/chrome/browser@123928 4ff67af0-8c30-449e-8e8b-ad334ec8d88c