Reverted due to cmpile errors:
chrome/browser/ui/views/tabs/tab_strip.cc:2318:18: error: field 'drop_index' is uninitialized when used here [-Werror,-Wuninitialized]
    : drop_index(drop_index),
                 ^
chrome/browser/ui/views/tabs/tab_strip.cc:2320:18: error: field 'point_down' is uninitialized when used here [-Werror,-Wuninitialized]
      point_down(point_down) {


Revert 180006 - Aura: Fix crash on dragging URL into tab strip

The widget for the window containing the drop-location arrow needs a parent
under Aura to be placed correctly.  A parent or context for each widget is
required due to https://codereview.chromium.org/11829040/

BUG=173229
TEST=Open two tabs, verify you can drag a blue URL link into the space between the two tabs in the tab strip. The URL should open in a new tab and Chrome should not crash.

Review URL: https://codereview.chromium.org/12089084

TBR=jamescook@chromium.org
Review URL: https://codereview.chromium.org/12092099

git-svn-id: http://src.chromium.org/svn/trunk/src/chrome/browser@180009 4ff67af0-8c30-449e-8e8b-ad334ec8d88c